### ISSUE TITLE
Why does the library limit recipients only to Czech and Slovak phone numbers?

### ISSUE THREAD

**Issue by Revisor** [simPod/SMSManager#2]
```
if (! (preg_match('/^\+420(?:(?:60[1-8]|7(?:0[2-5]|[2379]\d))\d{6})$/', $recipient)
    || (
        preg_match(
            '/^\+4219(?:0(?:[1-8]\d|9[1-9])|(?:1[0-24-9]|4[04589]|50)\d)\d{5}$/',
            $recipient
        )
        && $type !== RequestType::getRequestTypeLow()
    ))
```
Btw. not very readable, but why is the condition there at all?

**Comment by simPod** [comment]
At the time I was using the service this was the regex they used (if I remember correctly). Will check with them tmrw and get back ;)

**Comment by Revisor** [comment]
Thank you.

**Comment by simPod** [comment]
Just looking into it, maybe I'll remove the validation and leave it to the server side. That would be wiser I guess.
