### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by Revisor** [simPod/SMSManager#3]
Could you please tag a release?

**Comment by simPod** [comment]
Sure, just to confirm, is it all working for you?

**Comment by Revisor** [comment]
I haven't tried it yet, but will soon. If you're already using it in production, I would tag a 1.0 release.

**Comment by simPod** [comment]
I don't have any production usecase unfortunatelly. I have ported and refactorted a bit my old lib I don't have access to anymore.

Tagged prerelease https://github.com/simPod/SMSManager/releases/tag/v0.1-beta

**Comment by Revisor** [comment]
Well then I'll by the first to try it and let you know.
Thank you.
