### ISSUE TITLE
Authorize API requests with Apikey

### ISSUE THREAD

**Issue by JanBukva** [simPod/SMSManager#4]
With help of the https://smsmanager.cz/api/xml documentation I was able to successfully send SMS with the new Apikey field.
Otherwise I'm getting Unauthorized exception. Was trying to use Email&Password and Email&Token combination.

https://github.com/simPod/SMSManager/blob/5eac223f2e4ab7c570077d1999eccf3e7a3b66a4/src/ApiSmsManager.php#L78-L80

```php
        $requestHeader->addChild('Apikey', $this->password);
```

I'm testing this with a brand new SMSManager account, the old library LS/SMSManager is still working for LS.

```
In SendingFailed.php line 18:
                                                                                                  
  Sending failed for "+420xxxxxxxxx" because "The username or password you entered is incorrect"  
```

**Comment by simPod** [comment]
Can you verify with SMSManager.cz and eventually send PR?
